version: '3.4'

services:
  user.service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: User.Service/Dockerfile
    depends_on:
      - "user.database"
    networks:
       - kdvmanager-network

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.API/Dockerfile
    networks:
       - kdvmanager-network

  user.database:
     image: postgres:latest
     restart: always
     environment:
         POSTGRES_PASSWORD: postgres
     volumes:
       - users_data:/var/lib/postgresql/data
     networks:
       - kdvmanager-network

volumes:
  users_data:

networks:
  kdvmanager-network:
    driver: bridge